[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.black]
line-length = 120
target-version = ["py35"]

[tool.setuptools_scm]
write_to = "rsconnect_jupyter/version.py"
local_scheme = ""